FROM codesimple/elm:0.19 as elmBuilder
ENV BUILD=/app
RUN mkdir -p $BUILD
RUN mkdir -p $BUILD/dist
WORKDIR $BUILD
COPY ./Elm/src ./src
COPY ./Elm/elm.json .
RUN elm make ./src/Main.elm --output ./dist/todo.js

FROM fpco/stack-build:lts-14.6 as haskellBuilder

ENV LANG en_US.UTF-8
ENV PATH /root/.local/bin:$PATH

RUN mkdir -p /app
RUN mkdir -p /app/dist
WORKDIR /app

COPY ./Backend/Haskell/stack.yaml ./Backend/Haskell/TodoServer.cabal ./
RUN stack setup && stack install --dependencies-only

COPY ./BackEnd/Haskell .
RUN make deploy


FROM fpco/stack-run:lts-14.6
EXPOSE 8080

ENV LANG en_US.UTF-8

RUN mkdir -p /app
WORKDIR /app
COPY --from=haskellBuilder /dist /app

RUN mkdir -p static
COPY --from=haskellBuilder /app/static .
COPY --from=elmBuilder /app/dist/todo.js ./static/

RUN useradd app
USER app

ENTRYPOINT [ ]
CMD ["/app/TodoServer-exe"]