FROM codesimple/elm:0.19 as elmBuilder
ENV BUILD=/app
RUN mkdir -p $BUILD && mkdir -p $BUILD/dist && mkdir -p $BUILD/static
WORKDIR $BUILD
COPY ./Elm/package.json .
COPY ./Elm/package-lock.json .
RUN npm install
RUN cp ./node_modules/todomvc-app-css/index.css ./dist/index.css && cp ./node_modules/todomvc-common/base.css ./dist/base.css
COPY ./Elm/static ./static
RUN cp ./static/app.css ./dist/app.css
COPY ./Elm/src ./src
COPY ./Elm/elm.json .
RUN npx parcel build ./static/embedded.js -o todo.js --no-source-maps

FROM fpco/stack-build:lts-14.6 as haskellBuilder

ENV LANG en_US.UTF-8
ENV PATH /root/.local/bin:$PATH

RUN mkdir -p /app
RUN mkdir -p /app/dist
WORKDIR /app

COPY ./Backend/Haskell/stack.yaml ./Backend/Haskell/TodoServer.cabal ./
RUN stack setup && stack install --dependencies-only

COPY ./Backend/Haskell .
RUN make deploy


FROM ubuntu:18.04  
EXPOSE 8080

RUN apt-get update && apt-get install -y libgmp-dev && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app && mkdir -p /data
WORKDIR /app
COPY --from=haskellBuilder /app/dist /app

RUN mkdir -p static
COPY --from=elmBuilder /app/dist ./static

RUN useradd app && chown -hR app /app && chown -hR app /data
USER app

ENTRYPOINT ["/app/TodoServer-exe", "/data/settings.yaml"]