version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Docker/app/dockerfile
    container_name: todo-app
    restart: unless-stopped
    command: "/app/TodoServer-exe"
    environment:
      PORT: 8080